filebeat.inputs:
  - type: log
    paths:
      - /var/log/mylogs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  # If using security:
  # username: "elastic"
  # password: "yourpassword"

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
