version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: rate-api-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rate-api-postgres-db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data:
